AWSTemplateFormatVersion: 2010-09-09
Description: 'Template with explicit cfn_nag issues for demonstration purposes'
Resources:
  s3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
